# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(1024, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginPage.sizePolicy().hasHeightForWidth())
        LoginPage.setSizePolicy(sizePolicy)
        LoginPage.setMaximumSize(QtCore.QSize(1024, 727))
        self.Login_Background = QtWidgets.QLabel(LoginPage)
        self.Login_Background.setGeometry(QtCore.QRect(0, 0, 1024, 727))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_Background.sizePolicy().hasHeightForWidth())
        self.Login_Background.setSizePolicy(sizePolicy)
        self.Login_Background.setMinimumSize(QtCore.QSize(1024, 727))
        self.Login_Background.setMaximumSize(QtCore.QSize(1024, 727))
        self.Login_Background.setText("")
        self.Login_Background.setObjectName("Login_Background")
        self.Login_UsernameInput = QtWidgets.QPlainTextEdit(LoginPage)
        self.Login_UsernameInput.setGeometry(QtCore.QRect(580, 140, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(14)
        self.Login_UsernameInput.setFont(font)
        self.Login_UsernameInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Login_UsernameInput.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Login_UsernameInput.setObjectName("Login_UsernameInput")
        self.Login_PasswordInput = QtWidgets.QPlainTextEdit(LoginPage)
        self.Login_PasswordInput.setGeometry(QtCore.QRect(580, 290, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(14)
        self.Login_PasswordInput.setFont(font)
        self.Login_PasswordInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Login_PasswordInput.setObjectName("Login_PasswordInput")
        self.Login_LoginButton = QtWidgets.QPushButton(LoginPage)
        self.Login_LoginButton.setGeometry(QtCore.QRect(580, 450, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(14)
        self.Login_LoginButton.setFont(font)
        self.Login_LoginButton.setFlat(False)
        self.Login_LoginButton.setObjectName("Login_LoginButton")
        self.Login_CancelButton = QtWidgets.QPushButton(LoginPage)
        self.Login_CancelButton.setGeometry(QtCore.QRect(730, 450, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(14)
        self.Login_CancelButton.setFont(font)
        self.Login_CancelButton.setObjectName("Login_CancelButton")
        self.Login_PasswordLabel = QtWidgets.QLabel(LoginPage)
        self.Login_PasswordLabel.setGeometry(QtCore.QRect(580, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Login_PasswordLabel.setFont(font)
        self.Login_PasswordLabel.setObjectName("Login_PasswordLabel")
        self.Login_UsernameLabel = QtWidgets.QLabel(LoginPage)
        self.Login_UsernameLabel.setGeometry(QtCore.QRect(580, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        self.Login_UsernameLabel.setFont(font)
        self.Login_UsernameLabel.setObjectName("Login_UsernameLabel")
        self.Login_RegisterButton = QtWidgets.QPushButton(LoginPage)
        self.Login_RegisterButton.setGeometry(QtCore.QRect(580, 560, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(14)
        self.Login_RegisterButton.setFont(font)
        self.Login_RegisterButton.setFlat(False)
        self.Login_RegisterButton.setObjectName("Login_RegisterButton")

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Login"))
        self.Login_LoginButton.setText(_translate("LoginPage", "Login"))
        self.Login_CancelButton.setText(_translate("LoginPage", "Cancel"))
        self.Login_PasswordLabel.setText(_translate("LoginPage", "Password"))
        self.Login_UsernameLabel.setText(_translate("LoginPage", "Username"))
        self.Login_RegisterButton.setText(_translate("LoginPage", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QWidget()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
